name: build project

on:
  push:
    branches:
    
jobs:
  buildjob1:
    runs-on: ubuntu-latest
    steps:
    - name: buildstepjava
      uses: actions/checkout@v4
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

